services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    # image: seal-of-disapproval:latest
    build: .
    ports:
      - 3847:3847
    volumes:
      - ./seal_of_disapproval:/data/seal_of_disapproval
    env_file:
      - .env
    environment:
      - FORCE_SSL=${HOST}

  worker:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    build: .
    command: sh -c "cd /app && bundle exec sidekiq -C /app/config/sidekiq.yml"
    volumes:
      - ./seal_of_disapproval:/data/seal_of_disapproval
    env_file:
      - .env
    environment:
      - RAILS_ENV=production
      - WORKDIR=/data/seal_of_disapproval

  redis:
    image: redis:alpine
    volumes:
      - ./redis_data:/data

  postgres:
    image: postgres:18
    volumes:
      - './pg_data:/var/lib/postgresql/18/docker'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seal_of_disapproval
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    command: caddy reverse-proxy --from $HOST --to app:3847
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy:/data/caddy
    environment:
      - HOST=${HOST}
