services:
  app:
    build:
      context: .
      dockerfile: Containerfile.dev
      network: host
    ports:
      - 3847:3847
      - 3035:3035
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/seal_of_disapproval
      - REDIS_URL=redis://redis:6379/0
      - SHAKAPACKER_DEV_SERVER_HOST=0.0.0.0
      - USE_SMTP_IN_DEV=${USE_SMTP_IN_DEV:-false}
      - HOST=${HOST:-localhost}
      - SMTP_ADDRESS=${SMTP_ADDRESS:-}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_DOMAIN=${SMTP_DOMAIN:-}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - SMTP_FROM=${SMTP_FROM:-}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION:-plain}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    init: true
    stdin_open: true
    tty: true
    command: >
      sh -c "dos2unix bin/* Procfile.dev &&
             rm -f tmp/pids/server.pid &&
             bundle install &&
             bun install &&
             bundle exec rails db:prepare &&
             bundle exec foreman start -f Procfile.dev"

  postgres:
    image: postgres:18
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: seal_of_disapproval
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  bundle_cache:
  node_modules:
  pg_data:
  redis_data:
